name: validation

# defines the default parameters to call that shit
on:
  workflow_call:
    inputs:
      machine:
        required: false
        type: string
        default: self-hosted
      timeout:
        required: false
        type: number
        default: 240
      docker_image:
        required: true
        type: string


jobs:
  test:
    #...........................................................................
    # standard parameters: any runner, 20 min and latest container
    runs-on: ${{ inputs.machine }}
    timeout-minutes: ${{ inputs.timeout }}
    container:
      image: ${{ inputs.docker_image }}
    #...........................................................................
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      - name: build
        run: ARCH_FILE=make_arch/make.docker make test -j 4
      # run the tests
      - name: run
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 7 ./h3lpr_test

