name: pull request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

jobs:
  build-h3lpr:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/module_build_test.yml
    with:
      docker_image: vanreeslab/murphy_ci:v1.11

  # if the normal builds have been successful we can try to build the tests
  validation:
    if: ${{ !github.event.pull_request.draft }}
    needs: [build-h3lpr]
    uses: ./.github/workflows/module_validation.yml
    with:
      docker_image: vanreeslab/murphy_ci:v1.11
